disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - switch_case_alignment
 - identifier_name
 - line_length
 - function_body_length
 - cyclomatic_complexity
 - type_body_length
 - statement_position
 - implicit_getter
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
